{"identifier":{"url":"doc:\/\/ATProtoKit\/documentation\/ATProtoKit\/ATRequestPrepareError\/failedAfterRetries","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atprotokit\/atrequestprepareerror\/failedafterretries"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The request failed after several retries."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAfterRetries"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/ATProtoKit\/documentation\/ATProtoKit","doc:\/\/ATProtoKit\/documentation\/ATProtoKit\/ATProtoError","doc:\/\/ATProtoKit\/documentation\/ATProtoKit\/ATRequestPrepareError"]]},"metadata":{"roleHeading":"Case","modules":[{"name":"ATProtoKit"}],"role":"symbol","title":"ATRequestPrepareError.failedAfterRetries","symbolKind":"case","externalID":"s:10ATProtoKit21ATRequestPrepareErrorO18failedAfterRetriesyA2CmF","remoteSource":{"fileName":"ATProtoError.swift","url":"https:\/\/github.com\/MasterJ93\/ATProtoKit\/tree\/main\/Sources\/ATProtoKit\/Errors\/ATProtoError.swift#L342"},"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedAfterRetries"}]},"sections":[],"references":{"atprotokit_icon.png":{"variants":[{"url":"\/images\/atprotokit_icon.png","traits":["1x","light"]}],"identifier":"atprotokit_icon.png","type":"image","alt":"A technology icon representing the ATProtoKit framework."},"doc://ATProtoKit/documentation/ATProtoKit/ATRequestPrepareError":{"abstract":[{"text":"An error type related to issues surrounding preparing a request to be sent.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ATRequestPrepareError"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ATRequestPrepareError","kind":"identifier"}],"identifier":"doc:\/\/ATProtoKit\/documentation\/ATProtoKit\/ATRequestPrepareError","url":"\/documentation\/atprotokit\/atrequestprepareerror","kind":"symbol","title":"ATRequestPrepareError"},"doc://ATProtoKit/documentation/ATProtoKit":{"images":[{"type":"icon","identifier":"atprotokit_icon.png"}],"identifier":"doc:\/\/ATProtoKit\/documentation\/ATProtoKit","type":"topic","url":"\/documentation\/atprotokit","role":"collection","kind":"symbol","abstract":[{"text":"Develop and manage client and server-side applications for the AT Protocol and Bluesky.","type":"text"}],"title":"ATProtoKit"},"doc://ATProtoKit/documentation/ATProtoKit/ATProtoError":{"url":"\/documentation\/atprotokit\/atprotoerror","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ATProtoError","kind":"identifier"}],"role":"symbol","title":"ATProtoError","abstract":[{"type":"text","text":"The base exception class for ATProtoKit."}],"kind":"symbol","identifier":"doc:\/\/ATProtoKit\/documentation\/ATProtoKit\/ATProtoError","type":"topic","navigatorTitle":[{"text":"ATProtoError","kind":"identifier"}]},"doc://ATProtoKit/documentation/ATProtoKit/ATRequestPrepareError/failedAfterRetries":{"abstract":[{"type":"text","text":"The request failed after several retries."}],"type":"topic","role":"symbol","url":"\/documentation\/atprotokit\/atrequestprepareerror\/failedafterretries","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedAfterRetries","kind":"identifier"}],"title":"ATRequestPrepareError.failedAfterRetries","identifier":"doc:\/\/ATProtoKit\/documentation\/ATProtoKit\/ATRequestPrepareError\/failedAfterRetries"}}}